# https://docs.gitlab.com/ee/ci/yaml/README.html

variables:
  COMMIT_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MASTER_IMAGE: $CI_REGISTRY_IMAGE:master

stages:
  - build
  - test

pytest-image:
  image: docker.io/docker:20.10
  stage: build
  script:
    # see https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#docker-caching-example,
    - |
      echo "$CI_REGISTRY_PASSWORD" |
      docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin 2>/dev/null
    - |
      docker pull $COMMIT_IMAGE ||
      docker pull $BRANCH_IMAGE ||
      docker pull $MASTER_IMAGE ||
      echo No cache images available
    - |
      docker build -f Dockerfile.test . -t $COMMIT_IMAGE -t $BRANCH_IMAGE \
        --build-arg PYTHON_VERSION=3.7 \
        --build-arg POETRY_VERSION=1.1.5 \
        --build-arg VERSIONS_FILE=min \
        --cache-from $COMMIT_IMAGE,$BRANCH_IMAGE,$MASTER_IMAGE
    - docker push $COMMIT_IMAGE
    - docker push $BRANCH_IMAGE

pytest-run:
  image: $COMMIT_IMAGE
  needs:
    - pytest-image
  timeout: 5m
  stage: test
  script:
    - cd /converters
    - poetry run pytest --no-migrations
