ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}

ARG POETRY_VERSION
RUN pip install poetry${POETRY_VERSION:+==}${POETRY_VERSION}

WORKDIR converters
RUN poetry config virtualenvs.in-project true
COPY pyproject.toml ./pyproject.toml
# do this now to cache the base build, which will speed up the later steps when run again
RUN poetry install --no-dev

ARG VERSIONS_FILE
RUN test -n "${VERSIONS_FILE}" || ! echo "Must pass VERSIONS_FILE as a --build-arg"
COPY test_version_combinations/${VERSIONS_FILE} version_combination

RUN mv pyproject.toml pyproject-base.toml
COPY build_scripts build_scripts
RUN bash build_scripts/build_versioned_pyproject pyproject-base.toml version_combination pyproject.toml
RUN poetry install -E all

COPY converters converters
COPY tests tests
COPY django-test-site django-test-site

ENV PYTHONPATH="django-test-site"
ENV DJANGO_SETTINGS_MODULE="django_site.settings"
